const data =
{
    "DataTable": {
        "xs:schema": {
            "-id": "NewDataSet",
            "-xmlns": "",
            "-xmlns:xs": "http://www.w3.org/2001/XMLSchema",
            "-xmlns:msdata": "urn:schemas-microsoft-com:xml-msdata",
            "xs:element": {
                "-name": "NewDataSet",
                "-msdata:IsDataSet": "true",
                "-msdata:MainDataTable": "dtResult",
                "-msdata:UseCurrentLocale": "true",
                "xs:complexType": {
                    "xs:choice": {
                        "-minOccurs": "0",
                        "-maxOccurs": "unbounded",
                        "xs:element": {
                            "-name": "dtResult",
                            "xs:complexType": {
                                "xs:sequence": {
                                    "xs:element": [
                                        {
                                            "-name": "MA_DIEMDO",
                                            "-type": "xs:string",
                                            "-minOccurs": "0",
                                            "-self-closing": "true"
                                        },
                                        {
                                            "-name": "SO_CTO",
                                            "-type": "xs:string",
                                            "-minOccurs": "0",
                                            "-self-closing": "true"
                                        },
                                        {
                                            "-name": "IMPORT_KWH",
                                            "-type": "xs:decimal",
                                            "-minOccurs": "0",
                                            "-self-closing": "true"
                                        },
                                        {
                                            "-name": "EXPORT_KWH",
                                            "-type": "xs:decimal",
                                            "-minOccurs": "0",
                                            "-self-closing": "true"
                                        },
                                        {
                                            "-name": "IMPORT_VAR",
                                            "-type": "xs:decimal",
                                            "-minOccurs": "0",
                                            "-self-closing": "true"
                                        },
                                        {
                                            "-name": "EXPORT_VAR",
                                            "-type": "xs:decimal",
                                            "-minOccurs": "0",
                                            "-self-closing": "true"
                                        },
                                        {
                                            "-name": "Ia",
                                            "-type": "xs:decimal",
                                            "-minOccurs": "0",
                                            "-self-closing": "true"
                                        },
                                        {
                                            "-name": "Ib",
                                            "-type": "xs:decimal",
                                            "-minOccurs": "0",
                                            "-self-closing": "true"
                                        },
                                        {
                                            "-name": "Ic",
                                            "-type": "xs:decimal",
                                            "-minOccurs": "0",
                                            "-self-closing": "true"
                                        },
                                        {
                                            "-name": "Ua",
                                            "-type": "xs:decimal",
                                            "-minOccurs": "0",
                                            "-self-closing": "true"
                                        },
                                        {
                                            "-name": "Ub",
                                            "-type": "xs:decimal",
                                            "-minOccurs": "0",
                                            "-self-closing": "true"
                                        },
                                        {
                                            "-name": "Uc",
                                            "-type": "xs:decimal",
                                            "-minOccurs": "0",
                                            "-self-closing": "true"
                                        },
                                        {
                                            "-name": "Cosphi",
                                            "-type": "xs:decimal",
                                            "-minOccurs": "0",
                                            "-self-closing": "true"
                                        },
                                        {
                                            "-name": "NGAYGIO",
                                            "-type": "xs:string",
                                            "-minOccurs": "0",
                                            "-self-closing": "true"
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        },
        "diffgr:diffgram": {
            "-xmlns:msdata": "urn:schemas-microsoft-com:xml-msdata",
            "-xmlns:diffgr": "urn:schemas-microsoft-com:xml-diffgram-v1",
            "DocumentElement": {
                "dtResult": [
                    {
                        "-diffgr:id": "dtResult1",
                        "-msdata:rowOrder": "0",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6494.8928",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "767.5789",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "1",
                        "Ib": "1",
                        "Ic": "1",
                        "Ua": "233",
                        "Ub": "234",
                        "Uc": "234.4",
                        "Cosphi": "0.976",
                        "NGAYGIO": "2022-06-28 00:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult2",
                        "-msdata:rowOrder": "1",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6495.292",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "767.658",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "1.1",
                        "Ib": "1.1",
                        "Ic": "1.1",
                        "Ua": "232.8",
                        "Ub": "233.8",
                        "Uc": "234.1",
                        "Cosphi": "0.98",
                        "NGAYGIO": "2022-06-28 00:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult3",
                        "-msdata:rowOrder": "2",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6495.6312",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "767.7533",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "1",
                        "Ib": "1",
                        "Ic": "1",
                        "Ua": "230.1",
                        "Ub": "231",
                        "Uc": "231.3",
                        "Cosphi": "0.961",
                        "NGAYGIO": "2022-06-28 01:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult4",
                        "-msdata:rowOrder": "3",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6495.9368",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "767.8318",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "0.8",
                        "Ib": "0.9",
                        "Ic": "0.9",
                        "Ua": "229.6",
                        "Ub": "230.4",
                        "Uc": "230.7",
                        "Cosphi": "0.967",
                        "NGAYGIO": "2022-06-28 01:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult5",
                        "-msdata:rowOrder": "4",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6496.2344",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "767.9015",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "0.8",
                        "Ib": "0.9",
                        "Ic": "0.8",
                        "Ua": "230.4",
                        "Ub": "231.3",
                        "Uc": "231.6",
                        "Cosphi": "0.973",
                        "NGAYGIO": "2022-06-28 02:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult6",
                        "-msdata:rowOrder": "5",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6496.5464",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "767.9799",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "0.9",
                        "Ib": "0.9",
                        "Ic": "0.9",
                        "Ua": "230.8",
                        "Ub": "231.6",
                        "Uc": "232",
                        "Cosphi": "0.969",
                        "NGAYGIO": "2022-06-28 02:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult7",
                        "-msdata:rowOrder": "6",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6496.8156",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "768.0404",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "0.7",
                        "Ib": "0.8",
                        "Ic": "0.8",
                        "Ua": "231.5",
                        "Ub": "232.2",
                        "Uc": "232.6",
                        "Cosphi": "0.975",
                        "NGAYGIO": "2022-06-28 03:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult8",
                        "-msdata:rowOrder": "7",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6497.088",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "768.104",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "0.7",
                        "Ib": "0.8",
                        "Ic": "0.8",
                        "Ua": "231.6",
                        "Ub": "232.3",
                        "Uc": "232.6",
                        "Cosphi": "0.973",
                        "NGAYGIO": "2022-06-28 03:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult9",
                        "-msdata:rowOrder": "8",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6497.3568",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "768.1642",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "0.7",
                        "Ib": "0.8",
                        "Ic": "0.8",
                        "Ua": "232",
                        "Ub": "232.7",
                        "Uc": "233",
                        "Cosphi": "0.975",
                        "NGAYGIO": "2022-06-28 04:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult10",
                        "-msdata:rowOrder": "9",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6497.6404",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "768.2276",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "0.8",
                        "Ib": "0.8",
                        "Ic": "0.8",
                        "Ua": "232.3",
                        "Ub": "233",
                        "Uc": "233.4",
                        "Cosphi": "0.975",
                        "NGAYGIO": "2022-06-28 04:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult11",
                        "-msdata:rowOrder": "10",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6498.0684",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "768.3171",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "1.2",
                        "Ib": "1.3",
                        "Ic": "1.2",
                        "Ua": "232.3",
                        "Ub": "233.2",
                        "Uc": "233.7",
                        "Cosphi": "0.978",
                        "NGAYGIO": "2022-06-28 05:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult12",
                        "-msdata:rowOrder": "11",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6498.5504",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "768.4114",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "1.4",
                        "Ib": "1.4",
                        "Ic": "1.4",
                        "Ua": "232.2",
                        "Ub": "233.1",
                        "Uc": "233.5",
                        "Cosphi": "0.98",
                        "NGAYGIO": "2022-06-28 05:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult13",
                        "-msdata:rowOrder": "12",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6499.0444",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "768.5081",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "1.4",
                        "Ib": "1.4",
                        "Ic": "1.4",
                        "Ua": "232.6",
                        "Ub": "233.5",
                        "Uc": "234",
                        "Cosphi": "0.98",
                        "NGAYGIO": "2022-06-28 06:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult14",
                        "-msdata:rowOrder": "13",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6499.5984",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "768.6034",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "1.6",
                        "Ib": "1.6",
                        "Ic": "1.6",
                        "Ua": "231.5",
                        "Ub": "232.4",
                        "Uc": "232.9",
                        "Cosphi": "0.984",
                        "NGAYGIO": "2022-06-28 06:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult15",
                        "-msdata:rowOrder": "14",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6500.1752",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "768.7047",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "1.6",
                        "Ib": "1.7",
                        "Ic": "1.6",
                        "Ua": "230.8",
                        "Ub": "232",
                        "Uc": "232.6",
                        "Cosphi": "0.984",
                        "NGAYGIO": "2022-06-28 07:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult16",
                        "-msdata:rowOrder": "15",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6500.802",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "768.8147",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "1.9",
                        "Ib": "1.9",
                        "Ic": "1.8",
                        "Ua": "229.7",
                        "Ub": "231.2",
                        "Uc": "231.7",
                        "Cosphi": "0.984",
                        "NGAYGIO": "2022-06-28 07:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult17",
                        "-msdata:rowOrder": "16",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6501.4456",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "768.9398",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "1.9",
                        "Ib": "1.9",
                        "Ic": "1.9",
                        "Ua": "227.6",
                        "Ub": "229.3",
                        "Uc": "229.7",
                        "Cosphi": "0.98",
                        "NGAYGIO": "2022-06-28 08:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult18",
                        "-msdata:rowOrder": "17",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6502.1124",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "769.0608",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "1.9",
                        "Ib": "2",
                        "Ic": "1.9",
                        "Ua": "228.7",
                        "Ub": "230.5",
                        "Uc": "230.9",
                        "Cosphi": "0.983",
                        "NGAYGIO": "2022-06-28 08:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult19",
                        "-msdata:rowOrder": "18",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6502.754",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "769.1892",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "1.8",
                        "Ib": "1.9",
                        "Ic": "1.9",
                        "Ua": "230.1",
                        "Ub": "231.7",
                        "Uc": "232",
                        "Cosphi": "0.98",
                        "NGAYGIO": "2022-06-28 09:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult20",
                        "-msdata:rowOrder": "19",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6503.5724",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "769.3211",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2.4",
                        "Ib": "2.4",
                        "Ic": "2.4",
                        "Ua": "229.2",
                        "Ub": "231.5",
                        "Uc": "231.4",
                        "Cosphi": "0.986",
                        "NGAYGIO": "2022-06-28 09:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult21",
                        "-msdata:rowOrder": "20",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6504.4408",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "769.4981",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2.6",
                        "Ib": "2.6",
                        "Ic": "2.6",
                        "Ua": "227.2",
                        "Ub": "230",
                        "Uc": "229.7",
                        "Cosphi": "0.979",
                        "NGAYGIO": "2022-06-28 10:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult22",
                        "-msdata:rowOrder": "21",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6505.282",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "769.6643",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2.5",
                        "Ib": "2.4",
                        "Ic": "2.5",
                        "Ua": "227",
                        "Ub": "229.7",
                        "Uc": "229.3",
                        "Cosphi": "0.98",
                        "NGAYGIO": "2022-06-28 10:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult23",
                        "-msdata:rowOrder": "22",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6506.0992",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "769.81",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2.4",
                        "Ib": "2.4",
                        "Ic": "2.4",
                        "Ua": "227",
                        "Ub": "229.6",
                        "Uc": "229.2",
                        "Cosphi": "0.983",
                        "NGAYGIO": "2022-06-28 11:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult24",
                        "-msdata:rowOrder": "23",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6506.9312",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "769.9752",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2.5",
                        "Ib": "2.4",
                        "Ic": "2.5",
                        "Ua": "228.5",
                        "Ub": "230.8",
                        "Uc": "230.6",
                        "Cosphi": "0.98",
                        "NGAYGIO": "2022-06-28 11:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult25",
                        "-msdata:rowOrder": "24",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6507.7544",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "770.1188",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2.5",
                        "Ib": "2.3",
                        "Ic": "2.4",
                        "Ua": "228.5",
                        "Ub": "230.9",
                        "Uc": "230.4",
                        "Cosphi": "0.984",
                        "NGAYGIO": "2022-06-28 12:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult26",
                        "-msdata:rowOrder": "25",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6508.6016",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "770.2788",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2.5",
                        "Ib": "2.4",
                        "Ic": "2.5",
                        "Ua": "228.7",
                        "Ub": "231.1",
                        "Uc": "230.6",
                        "Cosphi": "0.982",
                        "NGAYGIO": "2022-06-28 12:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult27",
                        "-msdata:rowOrder": "26",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6509.4524",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "770.444",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2.6",
                        "Ib": "2.5",
                        "Ic": "2.5",
                        "Ua": "227",
                        "Ub": "229.4",
                        "Uc": "229.2",
                        "Cosphi": "0.981",
                        "NGAYGIO": "2022-06-28 13:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult28",
                        "-msdata:rowOrder": "27",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6510.2904",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "770.592",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2.5",
                        "Ib": "2.5",
                        "Ic": "2.5",
                        "Ua": "225.1",
                        "Ub": "227.3",
                        "Uc": "227.2",
                        "Cosphi": "0.984",
                        "NGAYGIO": "2022-06-28 13:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult29",
                        "-msdata:rowOrder": "28",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6511.12",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "770.7502",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2.5",
                        "Ib": "2.4",
                        "Ic": "2.5",
                        "Ua": "228.3",
                        "Ub": "230.6",
                        "Uc": "230.4",
                        "Cosphi": "0.981",
                        "NGAYGIO": "2022-06-28 14:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult30",
                        "-msdata:rowOrder": "29",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6511.9576",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "770.9113",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2.5",
                        "Ib": "2.4",
                        "Ic": "2.5",
                        "Ua": "227.4",
                        "Ub": "230",
                        "Uc": "229.8",
                        "Cosphi": "0.981",
                        "NGAYGIO": "2022-06-28 14:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult31",
                        "-msdata:rowOrder": "30",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6512.8152",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "771.0913",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2.6",
                        "Ib": "2.5",
                        "Ic": "2.5",
                        "Ua": "227.9",
                        "Ub": "230.6",
                        "Uc": "230.4",
                        "Cosphi": "0.978",
                        "NGAYGIO": "2022-06-28 15:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult32",
                        "-msdata:rowOrder": "31",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6513.5916",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "771.2599",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2.3",
                        "Ib": "2.3",
                        "Ic": "2.3",
                        "Ua": "227.6",
                        "Ub": "229.9",
                        "Uc": "229.9",
                        "Cosphi": "0.976",
                        "NGAYGIO": "2022-06-28 15:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult33",
                        "-msdata:rowOrder": "32",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6514.3404",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "771.4077",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2.3",
                        "Ib": "2.2",
                        "Ic": "2.2",
                        "Ua": "225.9",
                        "Ub": "227.9",
                        "Uc": "228",
                        "Cosphi": "0.98",
                        "NGAYGIO": "2022-06-28 16:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult34",
                        "-msdata:rowOrder": "33",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6515.0864",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "771.5569",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2.3",
                        "Ib": "2.2",
                        "Ic": "2.2",
                        "Ua": "226.9",
                        "Ub": "229",
                        "Uc": "229",
                        "Cosphi": "0.979",
                        "NGAYGIO": "2022-06-28 16:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult35",
                        "-msdata:rowOrder": "34",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6515.7528",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "771.6782",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2",
                        "Ib": "1.9",
                        "Ic": "2",
                        "Ua": "228.6",
                        "Ub": "230.4",
                        "Uc": "230.5",
                        "Cosphi": "0.983",
                        "NGAYGIO": "2022-06-28 17:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult36",
                        "-msdata:rowOrder": "35",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6516.3928",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "771.7947",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "1.9",
                        "Ib": "1.8",
                        "Ic": "1.8",
                        "Ua": "229.9",
                        "Ub": "231.7",
                        "Uc": "231.9",
                        "Cosphi": "0.983",
                        "NGAYGIO": "2022-06-28 17:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult37",
                        "-msdata:rowOrder": "36",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6517.0608",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "771.9223",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2",
                        "Ib": "1.9",
                        "Ic": "1.9",
                        "Ua": "230.4",
                        "Ub": "231.9",
                        "Uc": "232.4",
                        "Cosphi": "0.981",
                        "NGAYGIO": "2022-06-28 18:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult38",
                        "-msdata:rowOrder": "37",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6517.7356",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "772.0268",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2",
                        "Ib": "1.9",
                        "Ic": "1.9",
                        "Ua": "231.4",
                        "Ub": "233",
                        "Uc": "233.5",
                        "Cosphi": "0.987",
                        "NGAYGIO": "2022-06-28 18:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult39",
                        "-msdata:rowOrder": "38",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6518.434",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "772.1372",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2.1",
                        "Ib": "2",
                        "Ic": "2",
                        "Ua": "230.2",
                        "Ub": "231.9",
                        "Uc": "232.5",
                        "Cosphi": "0.987",
                        "NGAYGIO": "2022-06-28 19:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult40",
                        "-msdata:rowOrder": "39",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6519.1416",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "772.2468",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2.1",
                        "Ib": "2.1",
                        "Ic": "2",
                        "Ua": "230.1",
                        "Ub": "231.8",
                        "Uc": "232.5",
                        "Cosphi": "0.987",
                        "NGAYGIO": "2022-06-28 19:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult41",
                        "-msdata:rowOrder": "40",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6519.8636",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "772.3687",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2.2",
                        "Ib": "2.1",
                        "Ic": "2",
                        "Ua": "229.6",
                        "Ub": "231.6",
                        "Uc": "232.4",
                        "Cosphi": "0.985",
                        "NGAYGIO": "2022-06-28 20:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult42",
                        "-msdata:rowOrder": "41",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6520.5352",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "772.4671",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "2",
                        "Ib": "2",
                        "Ic": "1.9",
                        "Ua": "228.8",
                        "Ub": "230.6",
                        "Uc": "231.5",
                        "Cosphi": "0.988",
                        "NGAYGIO": "2022-06-28 20:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult43",
                        "-msdata:rowOrder": "42",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6521.1856",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "772.5678",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "1.9",
                        "Ib": "2",
                        "Ic": "1.8",
                        "Ua": "228.4",
                        "Ub": "230",
                        "Uc": "230.8",
                        "Cosphi": "0.987",
                        "NGAYGIO": "2022-06-28 21:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult44",
                        "-msdata:rowOrder": "43",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6521.8016",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "772.6651",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "1.8",
                        "Ib": "1.9",
                        "Ic": "1.7",
                        "Ua": "227.6",
                        "Ub": "229",
                        "Uc": "230.1",
                        "Cosphi": "0.987",
                        "NGAYGIO": "2022-06-28 21:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult45",
                        "-msdata:rowOrder": "44",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6522.3112",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "772.7448",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "1.4",
                        "Ib": "1.6",
                        "Ic": "1.4",
                        "Ua": "227.7",
                        "Ub": "228.9",
                        "Uc": "229.9",
                        "Cosphi": "0.987",
                        "NGAYGIO": "2022-06-28 22:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult46",
                        "-msdata:rowOrder": "45",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6522.7752",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "772.8112",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "1.3",
                        "Ib": "1.4",
                        "Ic": "1.3",
                        "Ua": "228.5",
                        "Ub": "229.6",
                        "Uc": "230.3",
                        "Cosphi": "0.988",
                        "NGAYGIO": "2022-06-28 22:30:00"
                    },
                    {
                        "-diffgr:id": "dtResult47",
                        "-msdata:rowOrder": "46",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6523.2384",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "772.8876",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "1.3",
                        "Ib": "1.4",
                        "Ic": "1.3",
                        "Ua": "229.4",
                        "Ub": "230.5",
                        "Uc": "231.3",
                        "Cosphi": "0.986",
                        "NGAYGIO": "2022-06-28 23:00:00"
                    },
                    {
                        "-diffgr:id": "dtResult48",
                        "-msdata:rowOrder": "47",
                        "-diffgr:hasChanges": "inserted",
                        "MA_DIEMDO": "20698013",
                        "SO_CTO": "20698013",
                        "IMPORT_KWH": "6523.6944",
                        "EXPORT_KWH": "0",
                        "IMPORT_VAR": "772.962",
                        "EXPORT_VAR": "123.9486",
                        "Ia": "1.3",
                        "Ib": "1.4",
                        "Ic": "1.2",
                        "Ua": "231.4",
                        "Ub": "232.1",
                        "Uc": "232.9",
                        "Cosphi": "0.986",
                        "NGAYGIO": "2022-06-28 23:30:00"
                    }
                ]
            }
        }
    }
}