apiVersion: v1
kind: Service
metadata:
  name: api-hub-server-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 32001
  selector:
    component: api-hub-server